### ISSUE TITLE
newest notebook error (sdxl forge)

### ISSUE THREAD

**Issue by eikibw** [gutris1/segsmaker#10]
*** Error running install.py for extension /home/studio-lab-user/forge/extensions/2sd-webui-reactor.
*** Command: "/home/studio-lab-user/.conda/envs/default/bin/python" "/home/studio-lab-user/forge/extensions/2sd-webui-reactor/install.py"
*** Error code: 1
*** stderr: /home/studio-lab-user/forge/extensions/2sd-webui-reactor/install.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
***   import pkg_resources
*** Traceback (most recent call last):
***   File "/home/studio-lab-user/forge/extensions/2sd-webui-reactor/install.py", line 49, in <module>
***     package: str, version: str | None = None, strict: bool = True
*** TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
Installing requirements for CivitAI Browser
Installing requirements for CivitAI Browser
Installing requirements for CivitAI Browser
Launching Web UI with arguments: --xformers --cuda-stream --pin-shared-memory --enable-insecure-extension-access --disable-console-progressbars --theme dark
Total VRAM 14931 MB, total RAM 15731 MB
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Always pin shared GPU memory
Device: cuda:0 Tesla T4 : native
VAE dtype: torch.float32
CUDA Stream Activated:  True
Traceback (most recent call last):
  File "/home/studio-lab-user/forge/launch.py", line 51, in <module>
    main()
  File "/home/studio-lab-user/forge/launch.py", line 47, in main
    start()
  File "/home/studio-lab-user/forge/modules/launch_utils.py", line 541, in start
    import webui
  File "/home/studio-lab-user/forge/webui.py", line 19, in <module>
    initialize.imports()
  File "/home/studio-lab-user/forge/modules/initialize.py", line 50, in imports
    shared_init.initialize()
  File "/home/studio-lab-user/forge/modules/shared_init.py", line 33, in initialize
    from modules import styles
  File "/home/studio-lab-user/forge/modules/styles.py", line 9, in <module>
    class PromptStyle(typing.NamedTuple):
  File "/home/studio-lab-user/forge/modules/styles.py", line 11, in PromptStyle
    prompt: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by gutris1** [comment]
> *** Error running install.py for extension /home/studio-lab-user/forge/extensions/2sd-webui-reactor. *** Command: "/home/studio-lab-user/.conda/envs/default/bin/python" "/home/studio-lab-user/forge/extensions/2sd-webui-reactor/install.py" *** Error code: 1 *** stderr: /home/studio-lab-user/forge/extensions/2sd-webui-reactor/install.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html *** import pkg_resources *** Traceback (most recent call last): *** File "/home/studio-lab-user/forge/extensions/2sd-webui-reactor/install.py", line 49, in *** package: str, version: str | None = None, strict: bool = True *** TypeError: unsupported operand type(s) for |: 'type' and 'NoneType' Installing requirements for CivitAI Browser Installing requirements for CivitAI Browser Installing requirements for CivitAI Browser Launching Web UI with arguments: --xformers --cuda-stream --pin-shared-memory --enable-insecure-extension-access --disable-console-progressbars --theme dark Total VRAM 14931 MB, total RAM 15731 MB xformers version: 0.0.26.post1 Set vram state to: NORMAL_VRAM Always pin shared GPU memory Device: cuda:0 Tesla T4 : native VAE dtype: torch.float32 CUDA Stream Activated: True Traceback (most recent call last): File "/home/studio-lab-user/forge/launch.py", line 51, in main() File "/home/studio-lab-user/forge/launch.py", line 47, in main start() File "/home/studio-lab-user/forge/modules/launch_utils.py", line 541, in start import webui File "/home/studio-lab-user/forge/webui.py", line 19, in initialize.imports() File "/home/studio-lab-user/forge/modules/initialize.py", line 50, in imports shared_init.initialize() File "/home/studio-lab-user/forge/modules/shared_init.py", line 33, in initialize from modules import styles File "/home/studio-lab-user/forge/modules/styles.py", line 9, in class PromptStyle(typing.NamedTuple): File "/home/studio-lab-user/forge/modules/styles.py", line 11, in PromptStyle prompt: str | None TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```
!rm -rf /home/studio-lab-user
```

**Comment by eikibw** [comment]
delete everything, restart everything—still the same error.
