### ISSUE TITLE
The ControlNet tab does not appear in the Web UI

### ISSUE THREAD

**Issue by AbedAchai1** [gutris1/segsmaker#12]
Why does this error appear when I run stable diffusion via any web UI, and some tabs in stable diffusion don't appear? This error was encountered during yesterday's installation. But apart from yesterday it was fine.

![image](https://github.com/gutris1/segsmaker/assets/136920434/8cef2adf-38da-412d-ad39-19730d96b4a7)
![image](https://github.com/gutris1/segsmaker/assets/136920434/af2f1b64-bfb4-4b6c-ad86-1947d08015e9)
![image](https://github.com/gutris1/segsmaker/assets/136920434/38bac616-44ac-4625-9366-cfbff4ce21dc)
![image](https://github.com/gutris1/segsmaker/assets/136920434/6d8ed6d9-e96b-4e86-9690-130770460aa9)
![image](https://github.com/gutris1/segsmaker/assets/136920434/7ff182c6-4477-4f36-8a11-e6f36454086c)

**Comment by gutris1** [comment]
wrong python
it should be python 3.10
not 3.9

**Comment by AbedAchai1** [comment]
but when I installed it for the first time, Python version 3.10.13 was right in the Conda tab

**Comment by AbedAchai1** [comment]
do I delete it again and reinstall conda from the beginning

**Comment by gutris1** [comment]
who know
I see that python 3.9 being used on the first image
![Screenshot_2024-05-25-11-30-17-470_com brave browser](https://github.com/gutris1/segsmaker/assets/132797949/7caa47e1-af5e-4f5c-90d6-4b3f9e42dd4e)

**Comment by AbedAchai1** [comment]
how can that be? Even though when you run conda, you initially install Python version 3.10.13

**Comment by AbedAchai1** [comment]
In fact, version 3.9 is included in the Web UI system. and the error is the same when running it, even though the initial version is the latest

![image](https://github.com/gutris1/segsmaker/assets/136920434/d67d5be5-af80-4737-a2db-c1a8bfea8c43)
![image](https://github.com/gutris1/segsmaker/assets/136920434/4d55e6cc-e065-4f94-8be1-daa60d234c8c)
![image](https://github.com/gutris1/segsmaker/assets/136920434/c6092410-de14-4e7b-9c9c-8ce57a49190a)
![image](https://github.com/gutris1/segsmaker/assets/136920434/dbcab123-52ea-4213-8d2b-85431538b684)

**Comment by gutris1** [comment]
reset sagemaker first
```
!rm -rf ~
```

**Comment by AbedAchai1** [comment]
in which tab?

**Comment by WetFoxx** [comment]
> reset sagemaker first
> 
> ```
> !rm -rf ~
> ```

It didn't work. Unfortunately, the error persisted.

**Comment by gutris1** [comment]
can you guys join this server https://discord.gg/k5BwmmvJJU
and tag me there in sagemaker channel
