### ISSUE TITLE
Login-Protected Models/LoRA Can't be Downloaded Even with Civitai Token

### ISSUE THREAD

**Issue by boredafk** [gutris1/segsmaker#13]
![Screenshot 2024-05-25 214519](https://github.com/gutris1/segsmaker/assets/170826056/689fa29c-5e5f-4455-b34b-3d283f44f61c)
Am I Missing Something? Is my Token Invalid?

**Comment by gutris1** [comment]
yes your token invalid

run
!rm -rf ~/your-civitai-api-key
then re run conda install to enter another api key

**Comment by boredafk** [comment]
Thanks, worked like a Magic, I also noticed that zrok tunnel didn't work. even with a token. it worked Before, but now it doesn't
Pinggy works just fine
