### ISSUE TITLE
problem of Zrok

### ISSUE THREAD

**Issue by RobbinTech** [gutris1/segsmaker#17]
Hello~
Is zrok out of service? It's not producing any output when I run it recently.
same thing happens even after changing several tokens.
If you are running it in the terminal, there is no proxy URL displayed.Currently, I can only use pinggy, which requires re-running every hour, which is a bit inconvenient.
`python zrok.py  zrok token --xformers --cuda-stream  --pin-shared-memory  --no-hashing  --enable-insecure-extension-access --disable-console-progressbars --theme dark`

**Comment by gutris1** [comment]
delete all environments on your zrok account by visiting api.zrok.io and login there

**Comment by RobbinTech** [comment]
> delete all environments on your zrok account by visiting api.zrok.io and login there

Deleted everything, it didn't work. I even tested with a new account, and it was the same.

**Comment by RobbinTech** [comment]
I also used a new SageMaker account to redeploy, and it was the same.

**Comment by gutris1** [comment]
> I also used a new SageMaker account to redeploy, and it was the same.

try running this command on an empty cell
```python
!~/.zrok/bin/zrok enable your_token
```
what's the output

**Comment by RobbinTech** [comment]
> > I also used a new SageMaker account to redeploy, and it was the same.
> 
> try running this command on an empty cell
> 
> ```python
> !~/.zrok/bin/zrok enable your_token
> ```
> 
> what's the output

[ERROR] you already have an enabled environment, zrok disable first before you zrok enable

**Comment by gutris1** [comment]
> > > I also used a new SageMaker account to redeploy, and it was the same.
> > 
> > 
> > try running this command on an empty cell
> > ```python
> > !~/.zrok/bin/zrok enable your_token
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > what's the output
> 
> [ERROR] you already have an enabled environment, zrok disable first before you zrok enable

that was common error, not really an error
running webui launch should give you the url

**Comment by RobbinTech** [comment]
> > > > I also used a new SageMaker account to redeploy, and it was the same.
> > > 
> > > 
> > > try running this command on an empty cell
> > > ```python
> > > !~/.zrok/bin/zrok enable your_token
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > what's the output
> > 
> > 
> > [ERROR] you already have an enabled environment, zrok disable first before you zrok enable
> 
> that was common error, not really an error running webui launch should give you the url

I checked carefully, and it's only this one that is "Running on local URL: http://127.0.0.1:7860".

Thank you for your answer. I'll use Pinggy or Ngrok first, as both of them are working properly.

**Comment by gutris1** [comment]
alright then
