### ISSUE TITLE
Zrok stopped working

### ISSUE THREAD

**Issue by matroxI** [gutris1/segsmaker#18]
ZROK stopped working.
Creating a new token and completely reinstalling the environment did not help.
Immediately after launch, the environment goes into idle without any errors.
Writing in zrok.py
```
    try:
        if len(sys.argv) < 2:
            sys.exit(1)

        token = sys.argv[1]
        launch_args = sys.argv[2:]

        zrok_enable(token)
        zrok_launch(launch_args)
    except Exception as e:
        print(e)
```
Nothing was output to the console

**Comment by gutris1** [comment]
> ZROK stopped working. Creating a new token and completely reinstalling the environment did not help. Immediately after launch, the environment goes into idle without any errors. Writing in zrok.py
> 
> ```
>     try:
>         if len(sys.argv) < 2:
>             sys.exit(1)
> 
>         token = sys.argv[1]
>         launch_args = sys.argv[2:]
> 
>         zrok_enable(token)
>         zrok_launch(launch_args)
>     except Exception as e:
>         print(e)
> ```
> 
> Nothing was output to the console

that should be an error on zrok side, because it still working properly on my runtime 
you want to see the output? 
here, paste these into jupyter cell and run it 

```python
!~/.zrok/bin/zrok enable your_token_here
```

```python
import multiprocessing

def run_launch():
    args = "--xformers --enable-insecure-extension-access --disable-console-progressbars --theme dark"
    get_ipython().system(f"python launch.py {args}")

def run_zrok():
    get_ipython().system("~/.zrok/bin/zrok share public localhost:7860 --headless")

%cd ~/asd
p1 = multiprocessing.Process(target=run_launch)
p2 = multiprocessing.Process(target=run_zrok)
p1.start()
p2.start()
p1.join()
p2.join()
```
