### ISSUE TITLE
trying to run this into a different ui , lightining ai 

### ISSUE THREAD

**Issue by ayush1268** [gutris1/segsmaker#19]
hello creator you absolutely did an awesome work creating this notebook works prefectly i was just testing if this could run into some different website like lightning ai same as sagemaker so when i tried to load this notebook into it i got me into some errors and please can you solve my issue if you want i would be really help me 
![scratch-studio ⚡ayushspecial1268 - Google Chrome 23-06-2024 22_54_51](https://github.com/gutris1/segsmaker/assets/71268103/d1877db3-8578-4475-a04d-96dcf30dad60)
![scratch-studio ⚡ayushspecial1268 - Google Chrome 23-06-2024 22_54_43](https://github.com/gutris1/segsmaker/assets/71268103/cbea6f46-8b92-428e-ac11-a477e25d8516)

**Comment by gutris1** [comment]
no. sorry

**Comment by ayush1268** [comment]
> no. sorry

no problm
