### ISSUE TITLE
zrok link not showing in cell

### ISSUE THREAD

**Issue by SpiritBeast** [gutris1/segsmaker#2]
![Capture](https://github.com/gutris1/segsmaker/assets/148947701/138733c7-452b-47c6-b17f-9e5696260f49)
I've followed the tutorial & get my token. when i start the cell, there is no zrok link.
Can you tell if there any steps i missed or how to fix this, thx

**Comment by gutris1** [comment]
zrok is not installed.
you can tag me on camenduru discord server https://discord.gg/k5BwmmvJJU
![image](https://github.com/gutris1/segsmaker/assets/132797949/74605bf8-9bd7-4c8d-9a41-14320d75283a)

**Comment by SpiritBeast** [comment]
> zrok is not installed. you can tag me on camenduru discord server https://discord.gg/k5BwmmvJJU ![image](https://private-user-images.githubusercontent.com/132797949/301100824-74605bf8-9bd7-4c8d-9a41-14320d75283a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTMwNjIsIm5iZiI6MTcwNjY5Mjc2MiwicGF0aCI6Ii8xMzI3OTc5NDkvMzAxMTAwODI0LTc0NjA1YmY4LTliZDctNGM4ZC05YTQxLTE0MzIwZDc1MjgzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQwOTE5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWQyNmI5ZjkyZjI4ZDczYWZmYWYyNzg0NzJiMjdhNjgzYjgxMGQ4YjMwOTE2OTAxZTI5M2ViNmUxZTNjODBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xb236HuLoT5C9tcRek5ibQBwp2I_-a_y4fRnI5kS98I)

why its not installed? i already run the previous cell

**Comment by gutris1** [comment]
> > zrok is not installed. you can tag me on camenduru discord server https://discord.gg/k5BwmmvJJU ![image](https://private-user-images.githubusercontent.com/132797949/301100824-74605bf8-9bd7-4c8d-9a41-14320d75283a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTMwNjIsIm5iZiI6MTcwNjY5Mjc2MiwicGF0aCI6Ii8xMzI3OTc5NDkvMzAxMTAwODI0LTc0NjA1YmY4LTliZDctNGM4ZC05YTQxLTE0MzIwZDc1MjgzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQwOTE5MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMWQyNmI5ZjkyZjI4ZDczYWZmYWYyNzg0NzJiMjdhNjgzYjgxMGQ4YjMwOTE2OTAxZTI5M2ViNmUxZTNjODBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Xb236HuLoT5C9tcRek5ibQBwp2I_-a_y4fRnI5kS98I)
> 
> why its not installed? i already run the previous cell, can you tell how to fix it pls

right click on anything, restart kernel, rerun previous cell, rerun that cell, thats it what I can tell

**Comment by SpiritBeast** [comment]
thx i'll try it
