### ISSUE TITLE
Conda Error

### ISSUE THREAD

**Issue by AbedAchai1** [gutris1/segsmaker#3]
Why does this error appear when running the cell, this happens several times when running, is there a solution?
![image](https://github.com/gutris1/segsmaker/assets/136920434/ba15a875-217c-4377-ad2b-03e479a3ec9b)

**Comment by gutris1** [comment]
> Why does this error appear when running the cell, this happens several times when running, is there a solution? ![image](https://private-user-images.githubusercontent.com/136920434/307209603-ba15a875-217c-4377-ad2b-03e479a3ec9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjM3MDEsIm5iZiI6MTcwODY2MzQwMSwicGF0aCI6Ii8xMzY5MjA0MzQvMzA3MjA5NjAzLWJhMTVhODc1LTIxN2MtNDM3Ny1hZDJiLTAzZTQ3OWEzZWM5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyM1QwNDQzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2VhMWUxNzE1ZGQ4MTcxZDQ2MjRkYjg4OTRlNGZhNGY3NTZhOGE4MGY0ZmUyM2NmOTk5ODk5NjUzMDNhY2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dhidh5P537MrEHclwBwhxqLnfdWFUdMYNq7bKJV49Z0)

it looks like you just deleted everything in the env, then tried to run the script without repairing the env to its default state first
it complaint about import error even with the requests library which is come with sagemaker conda default env. 

a simplest solution would be..
create a new cell, with the new untitled notebook and run this
!rm -rf /home/studio-lab-user
after that, stop your runtime and start again

**Comment by AbedAchai1** [comment]
ok, i'll try it

**Comment by AbedAchai1** [comment]
![image](https://github.com/gutris1/segsmaker/assets/136920434/dd1d3bc6-f898-4b1a-957b-1dd8355f90a8)
Now when I execute this column the zrok link doesn't appear, what's the solution?

**Comment by gutris1** [comment]
> ![image](https://private-user-images.githubusercontent.com/136920434/307516641-dd1d3bc6-f898-4b1a-957b-1dd8355f90a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzQ5NzMsIm5iZiI6MTcwODc3NDY3MywicGF0aCI6Ii8xMzY5MjA0MzQvMzA3NTE2NjQxLWRkMWQzYmM2LWY4OTgtNGIxYS05NTdiLTFkZDgzNTVmOTBhOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxMTM3NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NTVkZmI3NjNjZTc3MzFlY2M5OTRkOWEwMmE5NzE5ZDAxYWZkMDM4ZmM3MzhkYTA0OTM0NTU1NDc1MDJhZTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zXH5tZL037X_XvzfZvImf9POWIvTTfyj6KmxWWYyucc) Now when I execute this column the zrok link doesn't appear, what's the solution?

bro. get the new one https://github.com/gutris1/segsmaker/blob/main/Segsmaker_AnimateDiff_SD1.5.ipynb

**Comment by gutris1** [comment]
also you shouldn't expose your zrok token like that.
