### ISSUE TITLE
Lack of Instant ID models

### ISSUE THREAD

**Issue by MamboAI1** [gutris1/segsmaker#5]
Hi! thanks in advance for all the great work! 
I couldn´t find the Instant ID control Net models in the install options. I know they are located in this repo https://github.com/Mikubill/sd-webui-controlnet/discussions/2589
But have no idea on how to upload them directly from the url to the sagemaker proper directory. 
Can you help me please?

<img width="816" alt="Captura de pantalla 2024-03-17 a la(s) 05 04 37" src="https://github.com/gutris1/segsmaker/assets/163595353/8913d62f-1bb4-4dca-ac2c-f78ab5e46d06">

Thanks!

**Comment by gutris1** [comment]
7ebe74eafd406d8a2c439f8970af31b94aacf82e
