### ISSUE TITLE
Thank you so much for making the notebook, can you update the kaggle notebook?

### ISSUE THREAD

**Issue by huameiwei-vc** [gutris1/segsmaker#7]
I prefer to use kaggle because kaggle can run for a longer period of time, but I got an error with your kaggle notebook, can you update the kaggle notebook when you have time? Thank you very much.

**Comment by gutris1** [comment]
![a](https://media1.tenor.com/m/3DnfD3OJNScAAAAC/katekyo-hitman-reborn-anime.gif)
